### ISSUE TITLE
Add error handling and notification service

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-winter-2023-2024-lime#1]
Use https://www.npmjs.com/package/react-toastify for notification service.
Also add error handling in the middleware

**Comment by nikita-remeslov** [comment]
Link PR please

**Comment by ivanbilobrov07** [comment]
[PR](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/pull/25)
