### ISSUE TITLE
ENHANCEMENT: Log in button should be in the normal state with empty mandatory fields and after negative validation

### ISSUE THREAD

**Issue by Olena-Olenka** [BinaryStudioAcademy/bsa-winter-2023-2024-lime#102]
Log in button should be in the normal state with empty mandatory fields and after negative validation of values in the fields. Error message is displayed under empty field/field with invalid value after user clicks on Log in button. Logic of front-end validation should be aligned with the way it was implemented on Sign up page.

**Comment by nikita-remeslov** [comment]
@MarharytaR Could you review this?

**Comment by MarharytaR** [comment]
@nikita-remeslov It makes sense. Sign-up is more user-friendly and it would be better to do the same UX logic for the sign-in page to unify them and make both pages user-friendly. What do you think?

**Comment by Olena-Olenka** [comment]
I ask to consider applying the same enhancement to the Signup page, for consistency

**Comment by Olena-Olenka** [comment]
Imlemented partially, waiting for [147]([#147](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/issues/147)

**Comment by Olena-Olenka** [comment]
Fixed all but for bug described in this [ticket](https://github.com/orgs/BinaryStudioAcademy/projects/23/views/1?pane=issue&itemId=53805566)
