### ISSUE TITLE
Add OpenAI api integration

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-winter-2023-2024-lime#106]
Create a service which makes an integration with OpenAI api
You can use this: https://www.npmjs.com/package/openai
For now it would be enough if you create a service and test whether it works.
Later we will implement the integration with our app's needs
Regarding the openai model I suggest using gpt-3.5-turbo-0125 but its up to you, maybe you will find something that fits our project better

**Comment by Olena-Olenka** [comment]
Waiting for endpoints
