### ISSUE TITLE
BUG: The error "Passwords must be identical" is displayed on the "Sign up" page after user enters equal passwords but fills "Confirm password" field first

### ISSUE THREAD

**Issue by RostkoS** [BinaryStudioAcademy/bsa-winter-2023-2024-lime#115]
### Describe your issue

The error "Passwords must be identical" is displayed on the "Sign up" page after user enters equal passwords but fills "Confirm password" field before the "Password" field

### Steps to reproduce

1. Enter URL http://lime.eu-north-1.elasticbeanstalk.com/sign-up in browser.
2. Enter valid input in the "Confirm password" field
3. Enter the same value into the "Password" field
4. Pay attention to the error message displayed under "Confirm password" field

### What was the actual result?

The error "Passwords must be identical"  is displayed on the "Sign up" page after user enters equal passwords but fills "Confirm password" field before the "Password" field

### What was the expected result?

The error "Passwords must be identical" is hidden on the "Sign up" page after user enters equal passwords

### Put here any screenshots or videos (optional)

![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/124812752/23c98f75-8501-414e-89d7-460b4cf0fdcb)

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Minor (S4)

**Comment by SergiiTernytskyi** [comment]
This behaviour is changed by recommendations for ENHANCEMENT https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/issues/102

In the changes proposed Error messages are shown only after clicking the Submit button

**Comment by SergiiTernytskyi** [comment]
Now Error messages are shown only after pushing submit

**Comment by Olena-Olenka** [comment]
Shall be fixed with merging [102](https://github.com/orgs/BinaryStudioAcademy/projects/23/views/1?pane=issue&itemId=53709272)

**Comment by Olena-Olenka** [comment]
Can be reproduced after merging [102](https://github.com/orgs/BinaryStudioAcademy/projects/23/views/1?pane=issue&itemId=53709272)

![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/123622110/c7d213ca-9272-42ec-8d58-bff7203eeb83)
