### ISSUE TITLE
Protected Routing

### ISSUE THREAD

**Issue by dimapopovych** [BinaryStudioAcademy/bsa-winter-2023-2024-lime#12]
- Create an authorization plugin for endpoints 
- Plugin should augment request object with user information so it can be accessed later with req.user
- Add ability to exclude specific endpoints, such as sign-up and sign-in, through whitelisting.

**Comment by Olena-Olenka** [comment]
Token is required when trying to reach Sign In and Sign Up pages [Bugreport](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/issues/98 )

**Comment by Olena-Olenka** [comment]
To fullfill testing I am waiting until there will be implemented pages whose routes will be protected
