### ISSUE TITLE
Add activity widget

### ISSUE THREAD

**Issue by stpalamar** [BinaryStudioAcademy/bsa-winter-2023-2024-lime#122]
Create widget component

![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/26843161/f8655bf1-2c1f-4d85-8c7e-3043aa379d91)

**Comment by Olena-Olenka** [comment]
Steps activity widget on Home page is minimized more than other widgets in section when width of viewport is 768 and less
[#275](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/issues/275) (already fixed)
