### ISSUE TITLE
Add Goal widget

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-winter-2023-2024-lime#124]
- [ ] add goal widget
- [ ] make it reusable

![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/78347072/c3efd9ad-7fb1-4fe6-8526-af4567a3edeb)

**Comment by Olena-Olenka** [comment]
Done but for issues BUG: Elements of Goal widget on Home page don't correspond the design
[#279](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/issues/279)
