### ISSUE TITLE
Add achievements

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-winter-2023-2024-lime#138]
- [ ] add a new table for achievements
- [ ] add relationship between achievement and user
- [ ] add seed script to add a new achievement to DB (some achievement can be added each month)

doc - https://docs.google.com/document/d/1VQxwQBJV31FithP2wvaXjsV9vg8MO_cKZkkAglnsgN8/edit

**Comment by Olena-Olenka** [comment]
Waiting untill seed script will be run on server
