### ISSUE TITLE
Create notification component in header

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-winter-2023-2024-lime#139]
![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/105710998/4aeb8bfd-8b8e-4d9d-92bb-4b3c46548fd4)

Use this component from LMS as reference
When we click the icon we should see list of notifications

You can mock the data for now

**Comment by Olena-Olenka** [comment]
BUG: Notification pop-over blinks when clicking on unread message
[#465](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/issues/465)
Notification pop-over is not closed when clicking on browser Back button
[#494](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/issues/494)
Loader is displayed near Notifications icon when user removes notification
[#490](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/issues/490)
