### ISSUE TITLE
Add goals page

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-winter-2023-2024-lime#141]
![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/123622110/38c72cb0-33a0-49ff-bda9-1dc20765e1c4)

![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/123622110/f7976b9e-8b9e-45ec-bf8d-a861bb79e718)

mock the data for now until we have the api

SPECS from QA team (to be updated!)

Page can be reached in several ways: 

- click Avatar menu icon ⇒ Profile settings page ⇒ click tab Fitness Goals
- click Fitness Goals tab (name different from the design!!!!) in the side bar
- through modal window “Unleash Your Fitness Potential with LIME”

Modal window **Unleash Your Fitness Potential with LIME**:

- Contains message: Start your personalized journey to fitness. Set your first fitness goal today!  
- Redirects to the Fitness goals page, e.g. substring “fitness goal” is a link.
- provides user a possibility “Dont show me this message next time” 
- Can be closed without any other actions of the user

Modal window Unleash Your Fitness Potential with LIME! is displayed to the user:

- after registration
- after login if goals were not added to the profile and user didn’t confirm that he/she doesn't want to see this next time

On the Fitness goals page user can review:

- Congratulation with the completed goal
- Progress of current goals
- History of achievements

If no goals are set and no achievements by workouts gained, page is displayed with a 

- message “Unleash your fitness potential with new goals!” - wiget the same style as The first goal completed
- message “No goals yet” in Goals’ progress section
- achievement for joining LIME

User can set up custom goals. 

“**Set a new goal**” button is enabled and opens modal window “Set a new goal” 

Modal window “Set a new goal” .
Type of activity dropdown - options are identical to available in Preferences (Preferences are displayed on the top of the dropdown menu)
Frequency - with options:
- 1 time a day
- 2 times per day
- 1 time per week
- 2 times per week 
- 3 times per week
- 5 times per week
- 7 times per week
Distance (km) - label with unit of measurement - with a possibility to enter number  
Duration (min) - correct the label, not time! and unit of measurement -  with a possibility to enter number

Type of activity. Distance and Frequency dropdowns are mandatory and marked with asterisk. 

Button Save is enabled always. Validation is triggered with switching the focus away from the field. User should be displayed error messages under empty mandatory fields and fields with value of  invalid length or format.

User should be prevented from leaving the page with unsaved changes, e.g. with pop-up asking “Do you want to save changes?” and buttons “Save” and “Сancel”

**Congratulation section**: 
User is informed about the last goal completed in 100% with provided info about activity type and date of completeness
Information in section is updated as soon as new goal is completed

**Goals section:**

- For each gole should include name of the Activity, measurement of the fullfillment (value of distance etc), progressbar
- Progress of the goal is calculated using workout data.  
- Goal starts to be displayed in the section as soon as it is set.
- After fulfillment 100% goal is not displayed in this section, if it is displayed in Congratulation section. If it is not displayed in Congratulation section (it is not the only completed goal this day) it is displayed till the end of the day.
- User can review progress of all his goals if they are numerous, e.g. scrolling them down within the section. 

**Achievements section** 

- User can review history of Achievements. Each achievement has icon of the activity, title of the achievement, dateTime of the fullfillment
- User gets an achievement when his workout data fulfill requirements of the achievement - 

**Cycling**:

1. First 5 km
2. 20/50 km Journey.
3. 200/300 km in a month.
4. 2 h total per weekend.
5. AVG 25 km/h - 20 km ride
6. 1000 m height per month

**Running**:

1. First 1/5/10/21(half marathon)/42(marathon) km
2. First 30 min run
3. 100 km in a month
4. 10 km per weekend
5. 20 runs in a month

**Walking**:

1. First 5000/10,000/15000 steps in a day?
2. 10,000 steps everyday in 7 days 
3. 5 h per weekend
4. 100 km in a month
5. 10 km walk 
6. 500 kcal per walk

New achievement is displayed at the top of the section

**Comment by Olena-Olenka** [comment]
BUG: Distance between Goal banner and header is too large on Goals page
[#347](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/issues/347)
BUG: Goal banner is displayed without content on Goals page when screen width is 767 and less and if no goals are in progress
[#369](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/issues/369)
BUG: The achievements are not displayed fully on the Goals page
[#364](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/issues/364)
BUG: The loading icon is not centered on the Goals page
[#365](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/issues/365)
Content of Goals page is not centrally located
[#372](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/issues/372)
BUG: Background color of list items in Goals section on Goals page is different from design 
[#370](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/issues/370)
