### ISSUE TITLE
Sign Up Page

### ISSUE THREAD

**Issue by dimapopovych** [BinaryStudioAcademy/bsa-winter-2023-2024-lime#15]
![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/123622110/0de7cbb2-8ce5-4885-90f9-f8545248a1f0)

- Create a form and page according to the design. Exclude the "Continue with Google" and "Continue with Facebook" buttons.
- Implement the sign-up action flow. User should be added to Redux store upon successful registration
- Add validation. Should be shared 
- Log In link should redirect to sign in page

**SPECS from QA team**

**1.** User can register, filling in the registration form (screen 4). User is redirected to this page after clicking on “Create an account” link on Login page (screen 3)

**2.** Form contains fields “Email”, “Password”, “Confirm password”, all of them are mandatory (WITHOUT name field as in design!!!)

**Field  “Email”**:
- Placeholder should be as designed
- Should have minlength 6 characters and maxlength 320
- Should contain local part, @, domain part. 
**Local part:**
- Should contain from 1 to 64 characters.
- Uppercase and lowercase Latin letters (A-Z, a-z), digits (0-9), middle-placed non-consecutive dot (.), middle-placed hyphen (-), and underscore (_) are allowed, but not required
**Domain part:**
- Should contain from 4 to 254 characters.
- Uppercase and lowercase Latin letters (A-Z, a-z), digits 0-9, middle-placed hyphen (-) are allowed, but not required.
- Middle-placed non-consecutive dots (.) are allowed. One middle-placed dot is required. 
Spaces before and after Email string should be cropped 

**Field  “Password”**
- Placeholder is 6 bullets as designed
- Entered text is displayed masked as bullets for security. User can review unmasked password after clicking on “eye” icon 
- Should have minlength 6 characters and maxlength 12
- Uppercase and lowercase Latin letters (A-Z, a-z), digits (0-9) and special characters are allowed, but not required.
- Spaces before and after Password string should be cropped 

**Field  “Confirm Password”:**
- Placeholder are 6 bullets as designed
- Entered text is displayed masked as bullets for security. User can review unmasked password after clicking on “eye” icon 
- Should have minlength 6 characters and maxlength 12
- Uppercase and lowercase Latin letters (A-Z, a-z), digits (0-9) and special characters are allowed, but not required.
- Value should be equal to field “Password”
- Spaces before and after Confirm password string should be cropped

**3.** **Error messages:** 
- displayed under field with error value
- for empty field - Please fill out this field
- for invalid email value - Please enter a valid email
- for invalid password/confirm password length - Password must have from 6 to 12 characters
- for “Password” and “Confirm password” fields mismatch - "Passwords must be identical. Please try again" (displayed only under “Confirm password” field)
- for user with this email already exists - “User with this email already exists. Log in if it is you”. In case of this error, form is displayed with saved values in the fields

**4.** **“Sign up” button** (NOT “Log in” as it is in the design!):
- Should be inactive with empty mandatory fields
- Should be inactive after negative validation of length, format, password/confirm password mismatch.
-  Should be inactive after negative validation of email uniqueness.

**5.** User can register using social media (Google, Facebook).

**6.** After registering user is automatically authenticated.

![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/100519494/f79d8215-2ed7-49d2-a115-04d8f1500072)
[Design](https://www.figma.com/file/RRE9g9LIo3a1AK89HBlN6U/BSA_Lime?type=design&node-id=0-1&mode=design)

**Comment by JKaypa** [comment]
"User with this email already exists. Log in if it is you"
This message in which part of the form is displayed?

Also is needed to save input data to display it in inputs again if the submit response is an error message: user email already exists, if I understood well?

**Comment by Olena-Olenka** [comment]
Token is required when trying to reach Sign Up page Bug [here](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/issues/98)

**Comment by Olena-Olenka** [comment]
Rout menu is displayed on the page [Bugreport ](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/issues/99)
