### ISSUE TITLE
Sign In Page

### ISSUE THREAD

**Issue by dimapopovych** [BinaryStudioAcademy/bsa-winter-2023-2024-lime#16]
- Create a form and page according to the design. Exclude the "Continue with Google" and "Continue with Facebook" buttons.
- Implement the sign-in action flow. User should be added to Redux store upon successful login
- Add validation. Should be shared
- "Create and account" link should redirect to sign in page
 
**SPECS from QA Team**

**1.** Registered with email user can login using Login form

**2.** Form contains Email and Password fields, both mandatory

**Field  “Email”:**
- Placeholder should be as designed
- Should have minlength 6 characters and maxlength 320
- Should contain local part, @, domain part. 
**Local part:**
- Should contain from 1 to 64 characters.
- Uppercase and lowercase Latin letters (A-Z, a-z), digits (0-9), middle-placed non-consecutive dot (.), middle-placed hyphen (-), and underscore (_) are allowed, but not required
**Domain part:**
- Should contain from 4 to 254 characters.
- Uppercase and lowercase Latin letters (A-Z, a-z), digits 0-9, middle-placed hyphen (-) are allowed, but not required.
- Middle-placed non-consecutive dots (.) are allowed. One middle-placed dot is required.
Spaces before and after Email string should be cropped 

**Field  “Password”**
- Placeholder is 6 bullets as designed
- Entered text is displayed masked as bullets for security. User can review unmasked password after clicking on “eye” icon 
- Should have minlength 6 characters and maxlength 12
- Latin letters (A-Z, a-z), digits (0-9) and special characters are allowed
- Spaces before and after Password string should be cropped

**3.** Error messages:
- displayed under field with error value 
- for empty fields - Please fill out this field
- for invalid email - Please enter a valid email
- for invalid password length - Password must have from 6 to 12 characters
- for incorrect email or password - Incorrect email or password. Please try again. (displayed only under password field) In case of this error, form is displayed with saved values in the fields

**4.** “Log in” button:

- Should be inactive with empty mandatory fields
- Should be inactive after negative validation of the length and format of email or password 
- Should be inactive after negative validation of the correctness of email or password.

**5.** User can login using social media (Google, Facebook).

![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/100519494/c8df473e-7314-4ccb-819c-0e614660e755)
[Design](https://www.figma.com/file/RRE9g9LIo3a1AK89HBlN6U/BSA_Lime?type=design&node-id=0-1&mode=design)

**Comment by Olena-Olenka** [comment]
Rout menu is displayed on the page [Bugreport ](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/issues/99)

**Comment by Olena-Olenka** [comment]
Asterisk for labels of mandatory fields is needed [Bugreport ](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/issues/101)

**Comment by Olena-Olenka** [comment]
Semibold font is used for labels of the fields, placeholders, error messages [Bugreport ](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/issues/116)

**Comment by Olena-Olenka** [comment]
Error messages changes and disappearance is not triggered with the real-time changes in the field [Bugreport ](https://github.com/orgs/BinaryStudioAcademy/projects/23/views/1?pane=issue&itemId=53839855)
