### ISSUE TITLE
Add mandatory complexity requirements for passwords

### ISSUE THREAD

**Issue by Olena-Olenka** [BinaryStudioAcademy/bsa-winter-2023-2024-lime#170]
Mandatory complexity requirements for passwords should be added. Passwords must include at least one uppercase letter, one lowercase letter, one digit, and one special character.

User-friendly hint of the valid format of password should be provided to secure user from errors.

**Comment by nikita-remeslov** [comment]
Better to keep it for last week. To simplify testing
