### ISSUE TITLE
BUG: The email is not sent after using valid email in the "Forgot password" modal window

### ISSUE THREAD

**Issue by RostkoS** [BinaryStudioAcademy/bsa-winter-2023-2024-lime#189]
### Describe your issue

The email with the link to "Reset password" page is not sent after using valid email of the registered user in the "Forgot password" modal window.

### Steps to reproduce

1. Go to [http://lime.eu-north-1.elasticbeanstalk.com/sign-in](http://lime.eu-north-1.elasticbeanstalk.com/sign-in)
2. Click on the "Forgot password?" option
3. Enter valid email of the registered user
4. Click on the "Send" button
5. Pay attention to the "Something went wrong. Email has not sent" error displayed

### What was the actual result?

The email with the link to "Reset password" page is not sent after using valid email of the registered user in the "Forgot password" modal window. The "Something went wrong. Email has not sent" error is displayed. 

### What was the expected result?

The email with the link to "Reset password" page is sent after using valid email of the registered user in the "Forgot password" modal window.

### Put here any screenshots or videos (optional)

![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/124812752/a42fab34-0f6f-4269-87b3-a4287850f3f8)

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Blocker (S1)

**Comment by stpalamar** [comment]
Locally it works good, so I think env with sendgrid API KEY is not set in deployment

**Comment by stpalamar** [comment]
fixed
