### ISSUE TITLE
Add automatic calculation for goals and achievements

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-winter-2023-2024-lime#198]
- [ ] Add auto calculation for goals depending on workouts
- [ ] Add auto calculation for achievements depending on workouts

**Comment by Olena-Olenka** [comment]
Wrong extra achievements are received by user
[#536](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/issues/536)
