### ISSUE TITLE
Add chart for progress

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-winter-2023-2024-lime#199]
![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/78347072/16a11c89-78fb-4878-bf78-2a73575c2995)

- [ ] add period week, month, year
- [ ] use mocked data for now
- [ ] use chartjs - https://www.chartjs.org/

**Comment by nikita-remeslov** [comment]
@Olena-Olenka @RostkoS please add ticket to add chart to the home page

**Comment by Olena-Olenka** [comment]
Some issues may be improved/fixed in [#318](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/issues/318) and [#286](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/issues/286)
