### ISSUE TITLE
Add Home page

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-winter-2023-2024-lime#200]
![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/78347072/3017c46d-ecb3-4eb1-97a0-99511800635b)

- [ ] check both themes light and dark
- [ ] if we don't have some component leave a comment to add it

**Comment by ivanbilobrov07** [comment]
![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/112903531/cc68ead8-b615-4c8c-9918-24b660c396dd)


If I am not mistaken, we dont have this component

**Comment by Olena-Olenka** [comment]
Responsiveness shall be improved in [#286](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/issues/286)
