### ISSUE TITLE
Add Subnavigation menu for small screens

### ISSUE THREAD

**Issue by Olena-Olenka** [BinaryStudioAcademy/bsa-winter-2023-2024-lime#244]
Change the responsiveness of Sidebar making it wider or hidening after 1024 breakpoint and implement Subnavigation menu for small screens 

Try different variants and choose the best

![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/123622110/faf153c6-2d44-4295-b79a-0cf8f4b7ce8f)

![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/123622110/0641d4b1-bad2-48c7-a1ce-e890ebe94c00)

![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/123622110/d65624e0-4e33-48e8-a23e-10d018cf4eae)

**Comment by DavidCharif** [comment]
could be related with this task https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/issues/235

**Comment by DavidCharif** [comment]
As for existing discussion: https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/pull/251
