### ISSUE TITLE
BUG: Error message for invalid format of Weight and Height in Profile information is not user-friendly

### ISSUE THREAD

**Issue by Olena-Olenka** [BinaryStudioAcademy/bsa-winter-2023-2024-lime#305]
### Describe your issue

After negative validation on non-numeric value (letters, spaces, special characters excluding dot) of Weight and Height in Profile information, user is displayed error message "Expected number, received nan"
After negative validation on more than max value of Height in Profile information, user is displayed error message "Heiht should be from 0 to 0 sm"

### Steps to reproduce

1. Open https://live-in-motion-everyday.com/sign-in, login with valid credentials.
2. Navigate to Personal information page, clicking on gear icon in header.
3. Enter non-numeric value in the field Weight e.g. letters
4. Enter non-numeric value in the fields Heigh e.g. letters, switch focus to another element of field
5. Check if displayed error message is informative and user-friendly
6. Enter value more 300 in the field Height
7. Check if displayed error message is informative and user-friendly

### What was the actual result?

After negative validation on non-numeric value (letters, spaces, special characters excluding dot) of Weight and Height in Profile information, user is displayed error message "Expected number, received nan"
After negative validation on more than 300 value of Height in Profile information, user is displayed error message "Heiht should be from 0 to 0 sm"

### What was the expected result?

After negative validation on non-numeric value (letters, spaces, special characters excluding dot) of Weight and Height in Profile information, user is displayed informative and user friendly error message - e.g. Weight should only contain numbers and a decimal point or Please enter valid weight
After negative validation on more than 300 value of Height in Profile information, user is displayed error message "Heiht should be from 0 to 300 sm"

### Put here any screenshots or videos (optional)

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/123622110/2b8124ea-180f-4eb0-b996-b015a28b5147)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/123622110/69547a38-c456-4f35-9e91-b274b4a71e2f)

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Minor (S4)

**Comment by valery-chumak** [comment]
Will be closed via [303](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/issues/303)

**Comment by Olena-Olenka** [comment]
Retested, verified
