### ISSUE TITLE
BUG: Future values of date of birth can be saved on Profile information page

### ISSUE THREAD

**Issue by Olena-Olenka** [BinaryStudioAcademy/bsa-winter-2023-2024-lime#310]
### Describe your issue

- [ ] Future dates can be chosen from datepicker and saved as value of date of birth on Profile information page
- [ ] Future dates can be entered manually and saved as value of date of birth on Profile information page

### Steps to reproduce

1. Open https://live-in-motion-everyday.com/sign-in, login with valid credentials.
2. Navigate to Personal information page, clicking on gear icon in header, open DevTools.
3. Enter manually future date of birth
4. Click on Save
5. Check if data were saved in response body using Network tab in DevTools
6. Choose future date of birth from datepicker
7. Repeat steps 4-5

### What was the actual result?

Future dates can be either chosen from datepicker or entered manually and saved as value of date of birth on Profile information page

### What was the expected result?

Future values of date of birth can't be saved on Profile information page

### Put here any screenshots or videos (optional)

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/123622110/e8e9f8ef-8c0e-4155-ba20-3d5ed888ba22)

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Minor (S4)

**Comment by DavidCharif** [comment]
Does the app should have a minimum age for use, like  14 - 16?

**Comment by Olena-Olenka** [comment]
> Does the app should have a minimum age for use, like 14 - 16?

I guess it is not relevant for MVP

**Comment by Olena-Olenka** [comment]
Retested, verified
