### ISSUE TITLE
Add a Google Authorization

### ISSUE THREAD

**Issue by valery-chumak** [BinaryStudioAcademy/bsa-winter-2023-2024-lime#314]
- [ ] User can sign-in or sign-up using the Google Authorization service when he clicks on the corresponding button in Sign-in/Sign-up Page

![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/72942456/aae4a19f-a505-44fc-8a11-c13d8393a584)

**Comment by Olena-Olenka** [comment]
As an enhancement can be provided more user-friendly redirection after clicking Cancel on Google Auth page 

https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/123622110/7bced578-99b8-43ce-8deb-383ba91b5e79
