### ISSUE TITLE
Make switch theme icon more visible on sign in/up pages

### ISSUE THREAD

**Issue by jhladkov** [BinaryStudioAcademy/bsa-winter-2023-2024-lime#335]
![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/74872088/ddb389cd-bdd0-467c-a898-7e2b3a95b088)

We need to make the icon more visible against the background

**Comment by DavidCharif** [comment]
![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/f556a9b4-d3a3-40af-a84c-69cc1dce9c94)



![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/87c1dd4c-d87f-403b-8d8d-17143e2f9a15)

Maybe adding a background

![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/34ae37d2-452e-4795-bdf3-5a3f0ea6d051)



![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/8b9213a2-7f6f-48b4-8e32-5f03ccc9e47f)

Or is too much?

**Comment by jhladkov** [comment]
For me looks good :)
