### ISSUE TITLE
Sign Up

### ISSUE THREAD

**Issue by dimapopovych** [BinaryStudioAcademy/bsa-winter-2023-2024-lime#36]
Create Sign Up flow.
- Registration functionality
- fullName should be stored in separate table. Something like user_details
- Email should be unique
- Validation
- Create ER schema for DB structure and add to README
- Update swagger docs

SPECS from QA team

1. User can register, filling in the registration form (screen 4). User is redirected to this page after clicking on “Create an account” link on Login page (screen 3)

2. Form contains fields “Email”, “Password”, “Confirm password”, all of them are mandatory (WITHOUT name field)

Field “Email”:

Placeholder should be as designed
Should have minlength 6 characters and maxlength 320
Should contain local part, @, domain part.
Local part:
Should contain from 1 to 64 characters.
Uppercase and lowercase Latin letters (A-Z, a-z), digits (0-9), middle-placed non-consecutive dot (.), middle-placed hyphen (-), and underscore (_) are allowed, but not required
Domain part:
Should contain from 4 to 254 characters.
Uppercase and lowercase Latin letters (A-Z, a-z), digits 0-9, middle-placed hyphen (-) are allowed, but not required.
Middle-placed non-consecutive dots (.) are allowed. One middle-placed dot is required.
Spaces before and after Email string should be cropped
Field “Password”

Placeholder is 6 bullets as designed
Entered text is displayed masked as bullets for security. User can review unmasked password after clicking on “eye” icon
Should have minlength 6 characters and maxlength 12
Uppercase and lowercase Latin letters (A-Z, a-z), digits (0-9) and special characters are allowed, but not required.
Spaces before and after Password string should be cropped
Field “Confirm Password”:

Placeholder are 6 bullets as designed
Entered text is displayed masked as bullets for security. User can review unmasked password after clicking on “eye” icon
Should have minlength 6 characters and maxlength 12
Uppercase and lowercase Latin letters (A-Z, a-z), digits (0-9) and special characters are allowed, but not required.
Value should be equal to field “Password”
Spaces before and after Confirm password string should be cropped
3. Error messages:

displayed under field with error value
for empty field - Please fill out this field
for invalid email value - Please enter a valid email
for invalid password/confirm password length - Password must have from 6 to 12 characters
for “Password” and “Confirm password” fields mismatch - "Passwords must be identical. Please try again" (displayed only under “Confirm password” field)
for user with this email already exists - “User with this email already exists. Log in if it is you”. In case of this error, form is displayed with saved values in the fields
4. “Sign up” button (NOT “Log in” as it is in the design!):

Should be inactive with empty mandatory fields
Should be inactive after negative validation of length, format, password/confirm password mismatch.
Should be inactive after negative validation of email uniqueness.
5. User can register using social media (Google, Facebook).

6. After registering user is automatically authenticated.

**Comment by Olena-Olenka** [comment]
In case it will be helpful, the ticket with requirements for Sign Up Frontend is under the [link ](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/issues/15)
