### ISSUE TITLE
BUG: Content of Goals page is not centrally located

### ISSUE THREAD

**Issue by Olena-Olenka** [BinaryStudioAcademy/bsa-winter-2023-2024-lime#372]
### Describe your issue

Content of page without subnavigation - Goals page - is not centrally located

### Steps to reproduce

Pre-condition: user is logged in on https://live-in-motion-everyday.com/, responsive mode with screen width 1900 is selected in Toggle device in Devtools

1. Navigate to Goals page
2. Pay attention how content is located on the page

### What was the actual result?

Content of Goals page is not centrally located

### What was the expected result?

Content of all pages without subnavigation is fixed and centrally located - like on Overview page

### Put here any screenshots or videos (optional)

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/123622110/62094f84-83b0-4ad8-abce-6585897472bb)

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Minor (S4)

**Comment by nikita-remeslov** [comment]
@DavidCharif Link PR pls

**Comment by DavidCharif** [comment]
Already solved on https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/pull/379

**Comment by Olena-Olenka** [comment]
Retested, verified
