### ISSUE TITLE
Add Header component

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-winter-2023-2024-lime#41]
![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/78347072/2f18b1f1-d264-433e-b589-90b73fc98e2c)

**Comment by Olena-Olenka** [comment]
To take this ticket in Testing QA's are waiting until there will be implemented pages with header

**Comment by Olena-Olenka** [comment]
"Wellcome" message location in header doesn't correspond to design
[#215](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/issues/215)

**Comment by Olena-Olenka** [comment]
Size of the Logo in header is less than designed 
[#216](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/issues/216)
