### ISSUE TITLE
Enhancement: Public profile page should optionally contain private info - weight, height, age

### ISSUE THREAD

**Issue by Olena-Olenka** [BinaryStudioAcademy/bsa-winter-2023-2024-lime#435]
User should be provided a possibility to choose whether he/she wants to share personal info on Public progile page. E.g. check box for agreement to share information about age, weight, height may be included on Personal information page

**Comment by Olena-Olenka** [comment]
As for location, this question may be also discussed

**Comment by nikita-remeslov** [comment]
@valery-chumak link PR pls
