### ISSUE TITLE
BUG: User can't save valid date of birth on Personal information page

### ISSUE THREAD

**Issue by Olena-Olenka** [BinaryStudioAcademy/bsa-winter-2023-2024-lime#452]
### Describe your issue

User can't save valid date of birth on Profile information page: server error message is displayed, status code 422 is received on backend

### Steps to reproduce

1. Sign up on https://live-in-motion-everyday.com/sign-up
2. Navigate to Personal Information page, clicking on gear ion in header
3. Enter valid past date of birth
4. Pay attention to the error message displayed and server response

### What was the actual result?

User can't save valid date of birth on Profile information page: server error message is displayed to user. In response status code 422 is received  and error message {
    "details": [
        {
            "message": "Invalid date format. Use DD/MM/YYYY",
            "path": [
                "dateOfBirth"
            ]
        },
        {
            "message": "Date of birth can not be in the future",
            "path": [
                "dateOfBirth"
            ]
        }
    ],
    "errorType": "VALIDATION",
    "message": "[\n  {\n    \"validation\": \"regex\",\n    \"code\": \"invalid_string\",\n    \"message\": \"Invalid date format. Use DD/MM/YYYY\",\n    \"path\": [\n      \"dateOfBirth\"\n    ]\n  },\n  {\n    \"code\": \"custom\",\n    \"message\": \"Date of birth can not be in the future\",\n    \"path\": [\n      \"dateOfBirth\"\n    ]\n  }\n]"
}

### What was the expected result?

Data is saved, Profile information page is displayed with saved value of date of birth

### Put here any screenshots or videos (optional)

https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/123622110/8087a61c-34a7-42e4-9041-433d4519d144

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Major (S3)

**Comment by valery-chumak** [comment]
Fixed via #449

**Comment by nikita-remeslov** [comment]
Links PR pls

**Comment by Olena-Olenka** [comment]
Retested, verified
