### ISSUE TITLE
Add description for subscriptions

### ISSUE THREAD

**Issue by ArtemLymarenko** [BinaryStudioAcademy/bsa-winter-2023-2024-lime#468]

**Comment by Olena-Olenka** [comment]
![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/123622110/afca6d5c-bbcd-46c6-96f6-d9eaff2bd1e4)

Descriptions are not displayed on Subscriptions page. And please, fix this typo with lacking apostrophe in don't
