### ISSUE TITLE
Add email service

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-winter-2023-2024-lime#49]
Create an email service which we would later use in password reset logic and probably in other services.

Use [sendgrid](https://www.npmjs.com/package/@sendgrid/mail) for it.

For this task it would probably be enough to add the service, test if emails are sent and later we will connect it with password reset page

**Comment by ivanbilobrov07** [comment]
I have some problems with creating an account in sendgrid 
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/112903531/76141afd-dd4d-41b9-be33-02a186fb9660)

**Comment by ivanbilobrov07** [comment]
I wrote to support, but don't realy know if it helps us
