### ISSUE TITLE
Reset password page

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-winter-2023-2024-lime#54]
SPECS from QA team

Registered with email user can set up a new password 

**Happy path** 

1. Click on “Forgot Password” link on “Login” page - modal window  “Forgot password” is displayed.
2. Enter valid email and submit it on “Forgot password” modal window. 
3. Pop-up with message “Link for password reset was sent to your email. Check your inbox letters and follow the instructions. If you don’t see the email, please check your spam folder ” is displayed instead of “Forgot password” modal window for 5 seconds. After it disappears and Login page is displayed.
4.  Receive email with one-time link with expiration time 1 day, click on it and navigate to “Reset password” page (opened in the new browser tab) 
5. Enter new password, confirm it, submit it on “Reset password” page.
6.  Message “Your password has been successfully reset. You can now use it to log in” is displayed on “Reset password” page instead of inputs and buttons. Substring “log in” is a link to Login page.
7. Navigate to the “Login” page through the link on Reset password page. 
8. Login with the new password.

**Unhappy path, if link is expired**: after clicking on the link user is redirected to the page with error message “The password reset link you used has expired. Please request a new link to reset your password”.

**"Forgot password" modal window Elements:**

Title of the web form - Enter Your Email for Password Reset

Text input - title Email, placeholder [email@gmail.co](mailto:email@gmail.com)m
- Mandatory field
- Should have minlength 6 characters and maxlength 320
- Should contain local part, @, domain part.
**Local part:**
- Should contain from 1 to 64 characters.
- Uppercase and lowercase Latin letters (A-Z, a-z), digits (0-9), middle-placed non-consecutive dot (.), middle-placed hyphen (-), and underscore (_) are allowed, but not required
**Domain part:**
- Should contain from 4 to 254 characters.
- Uppercase and lowercase Latin letters (A-Z, a-z), digits 0-9, middle-placed hyphen (-) are allowed, but not required.
- Middle-placed non-consecutive dots (.) are allowed. One middle-placed dot is required.
Spaces before and after Email string should be cropped

**Button Send**
- Should be inactive with empty Email field
- Should be inactive after negative validation of length or format

**Button Cancel**
- cancels changes, closes pop-up

**X** element for pop-up closing

**Error messages**
- for empty field - “Please fill out this field”
- for invalid email value - “Please enter a valid email”
- for email, absent in DB - “No user with this email was found. Please enter a correct email”. Field email is not cleared in this case. 

**Reset password page Elements:**

Title of the web form - **Set Up Your New Password**

**Text field “New Password**”
- Mandatory field
- Placeholder is 6 bullets as designed
- Entered text is displayed masked as bullets for security. User can review unmasked password after clicking on “eye” icon
- Should have minlength 6 characters and maxlength 12
- Uppercase and lowercase Latin letters (A-Z, a-z), digits (0-9) and special characters are allowed, but not required.
- Spaces before and after Password string should be cropped

**Field “Confirm New Password”:**
- Mandatory field
- Placeholder are 6 bullets as designed
- Entered text is displayed masked as bullets for security. User can review unmasked password after clicking on “eye” icon
- Should have minlength 6 characters and maxlength 12
- Uppercase and lowercase Latin letters (A-Z, a-z), digits (0-9) and special characters are allowed, but not required.
- Value should be equal to field “Password”
- Spaces before and after Confirm password string should be cropped

**Button "Reset Password":**
- Should be inactive with empty mandatory fields
- Should be inactive after negative validation of length, password/confirm password mismatch.

**Error messages**
- displayed under field with error value
- for empty field - Please fill out this field
- for invalid password/confirm password length - Password must have from 6 to 12 characters
- for “Password” and “Confirm password” fields mismatch - "Passwords must be identical. Please try again" (displayed only under “Confirm password” field)

**Text of the letter with password recovery link** 

Hello!
You have recently requested to reset your password for your LIME. Live In Motion Everyday account. Please use the link below to reset it:
[Password Reset Link]
If you did not request a password reset, please ignore this email. This link is only valid for 24 hours.
For security reasons, we recommend that you do not share this link with anyone. If need further assistance, please contact our support team at [Support Email] .
We're here to support you on your fitness journey!
Best regards,
The LIME Team

**Comment by Olena-Olenka** [comment]
BUG: Width of the elements of the modal window for Password Reset starts to minimize not corresponding to the width of the modal
[#195](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/issues/195)

**Comment by Olena-Olenka** [comment]
BUG: The email is not sent after using valid email in the "Forgot password" modal window
[#189](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/issues/189)
