### ISSUE TITLE
BUG: Sent in chat message is not displayed untill user switches to the chat with another user 

### ISSUE THREAD

**Issue by Olena-Olenka** [BinaryStudioAcademy/bsa-winter-2023-2024-lime#563]
### Describe your issue

Sent in chat message is not displayed untill user switches to the chat with another user 

### Steps to reproduce

**Pre-condition:** User 1 has is just registered. 

1. Navigate to Friends page as User 1
2. Follow User 2
3. Click on message button on User's 2 card
4. Write a message and send it
5. Pay attention if message is displayed in chat

### What was the actual result?

Sent in chat message is not displayed untill user switches to the chat with another user 

### What was the expected result?

Sent in chat message is displayed immediately, as it was sent

### Put here any screenshots or videos (optional)

c

https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/123622110/56269e36-4052-4947-926d-10ed717e0031

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Critical (S2)

**Comment by DavidCharif** [comment]
On current deploy the message is being show on send message

https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/129c5d05-d763-49a6-aeb3-e41d827bb8af
