### ISSUE TITLE
Create Input component

### ISSUE THREAD

**Issue by dimapopovych** [BinaryStudioAcademy/bsa-winter-2023-2024-lime#6]
Create a reusable input component that aligns with the provided design specifications.
![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/100519494/cdd24279-6b48-45e1-928c-7508a75a863e)
[Design](https://www.figma.com/file/RRE9g9LIo3a1AK89HBlN6U/BSA_Lime?type=design&node-id=0-1&mode=design)

**Comment by nikita-remeslov** [comment]
@JKaypa Please unlink closed PR
