### ISSUE TITLE
Add Connections page to the Profile Settings

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-winter-2023-2024-lime#82]
- [ ] We should use our design (screenshot just example)
- [ ] Add option to connect Strava
- [ ] Add option to connect Google Fit

Disconnected state:
![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/78347072/8928ed56-7911-4be6-b252-301ef9f06dab)

Connected state:
![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/78347072/52e65edf-82ce-4790-86df-b29a85ccfb09)

**Comment by Olena-Olenka** [comment]
Waiting for the Profile page being deployed
