### ISSUE TITLE
Add ability to switch Light/Dark mode

### ISSUE THREAD

**Issue by dimapopovych** [BinaryStudioAcademy/bsa-winter-2023-2024-lime#93]
Current mode should be stored in local storage
https://tailwindcss.com/docs/dark-mode#basic-usage

**Comment by Olena-Olenka** [comment]
BUG: Light mode UI/UX defects 
[#192](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/issues/192)
